// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proxy.proto

package proxy

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TrafficSource struct {
	Region               string   `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	TrafficProvider      string   `protobuf:"bytes,2,opt,name=trafficProvider,proto3" json:"trafficProvider,omitempty"`
	MapProvider          string   `protobuf:"bytes,3,opt,name=mapProvider,proto3" json:"mapProvider,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrafficSource) Reset()         { *m = TrafficSource{} }
func (m *TrafficSource) String() string { return proto.CompactTextString(m) }
func (*TrafficSource) ProtoMessage()    {}
func (*TrafficSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{0}
}

func (m *TrafficSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficSource.Unmarshal(m, b)
}
func (m *TrafficSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficSource.Marshal(b, m, deterministic)
}
func (m *TrafficSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficSource.Merge(m, src)
}
func (m *TrafficSource) XXX_Size() int {
	return xxx_messageInfo_TrafficSource.Size(m)
}
func (m *TrafficSource) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficSource.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficSource proto.InternalMessageInfo

func (m *TrafficSource) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *TrafficSource) GetTrafficProvider() string {
	if m != nil {
		return m.TrafficProvider
	}
	return ""
}

func (m *TrafficSource) GetMapProvider() string {
	if m != nil {
		return m.MapProvider
	}
	return ""
}

type WayIdsStructure struct {
	WayId                []int64  `protobuf:"zigzag64,1,rep,packed,name=wayId,proto3" json:"wayId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WayIdsStructure) Reset()         { *m = WayIdsStructure{} }
func (m *WayIdsStructure) String() string { return proto.CompactTextString(m) }
func (*WayIdsStructure) ProtoMessage()    {}
func (*WayIdsStructure) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{1}
}

func (m *WayIdsStructure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WayIdsStructure.Unmarshal(m, b)
}
func (m *WayIdsStructure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WayIdsStructure.Marshal(b, m, deterministic)
}
func (m *WayIdsStructure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WayIdsStructure.Merge(m, src)
}
func (m *WayIdsStructure) XXX_Size() int {
	return xxx_messageInfo_WayIdsStructure.Size(m)
}
func (m *WayIdsStructure) XXX_DiscardUnknown() {
	xxx_messageInfo_WayIdsStructure.DiscardUnknown(m)
}

var xxx_messageInfo_WayIdsStructure proto.InternalMessageInfo

func (m *WayIdsStructure) GetWayId() []int64 {
	if m != nil {
		return m.WayId
	}
	return nil
}

type Flow struct {
	WayId                int64    `protobuf:"zigzag64,1,opt,name=wayId,proto3" json:"wayId,omitempty"`
	Speed                float32  `protobuf:"fixed32,2,opt,name=speed,proto3" json:"speed,omitempty"`
	TrafficLevel         int32    `protobuf:"varint,3,opt,name=trafficLevel,proto3" json:"trafficLevel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Flow) Reset()         { *m = Flow{} }
func (m *Flow) String() string { return proto.CompactTextString(m) }
func (*Flow) ProtoMessage()    {}
func (*Flow) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{2}
}

func (m *Flow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Flow.Unmarshal(m, b)
}
func (m *Flow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Flow.Marshal(b, m, deterministic)
}
func (m *Flow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Flow.Merge(m, src)
}
func (m *Flow) XXX_Size() int {
	return xxx_messageInfo_Flow.Size(m)
}
func (m *Flow) XXX_DiscardUnknown() {
	xxx_messageInfo_Flow.DiscardUnknown(m)
}

var xxx_messageInfo_Flow proto.InternalMessageInfo

func (m *Flow) GetWayId() int64 {
	if m != nil {
		return m.WayId
	}
	return 0
}

func (m *Flow) GetSpeed() float32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *Flow) GetTrafficLevel() int32 {
	if m != nil {
		return m.TrafficLevel
	}
	return 0
}

type FlowsStructure struct {
	Flow                 []*Flow  `protobuf:"bytes,1,rep,name=flow,proto3" json:"flow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlowsStructure) Reset()         { *m = FlowsStructure{} }
func (m *FlowsStructure) String() string { return proto.CompactTextString(m) }
func (*FlowsStructure) ProtoMessage()    {}
func (*FlowsStructure) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{3}
}

func (m *FlowsStructure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlowsStructure.Unmarshal(m, b)
}
func (m *FlowsStructure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlowsStructure.Marshal(b, m, deterministic)
}
func (m *FlowsStructure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlowsStructure.Merge(m, src)
}
func (m *FlowsStructure) XXX_Size() int {
	return xxx_messageInfo_FlowsStructure.Size(m)
}
func (m *FlowsStructure) XXX_DiscardUnknown() {
	xxx_messageInfo_FlowsStructure.DiscardUnknown(m)
}

var xxx_messageInfo_FlowsStructure proto.InternalMessageInfo

func (m *FlowsStructure) GetFlow() []*Flow {
	if m != nil {
		return m.Flow
	}
	return nil
}

type TrafficRequest struct {
	TrafficSource *TrafficSource `protobuf:"bytes,1,opt,name=trafficSource,proto3" json:"trafficSource,omitempty"`
	// Types that are valid to be assigned to WayIdFields:
	//	*TrafficRequest_All
	//	*TrafficRequest_WayId
	//	*TrafficRequest_WayIds
	WayIdFields          isTrafficRequest_WayIdFields `protobuf_oneof:"WayIdFields"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *TrafficRequest) Reset()         { *m = TrafficRequest{} }
func (m *TrafficRequest) String() string { return proto.CompactTextString(m) }
func (*TrafficRequest) ProtoMessage()    {}
func (*TrafficRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{4}
}

func (m *TrafficRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficRequest.Unmarshal(m, b)
}
func (m *TrafficRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficRequest.Marshal(b, m, deterministic)
}
func (m *TrafficRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficRequest.Merge(m, src)
}
func (m *TrafficRequest) XXX_Size() int {
	return xxx_messageInfo_TrafficRequest.Size(m)
}
func (m *TrafficRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficRequest proto.InternalMessageInfo

func (m *TrafficRequest) GetTrafficSource() *TrafficSource {
	if m != nil {
		return m.TrafficSource
	}
	return nil
}

type isTrafficRequest_WayIdFields interface {
	isTrafficRequest_WayIdFields()
}

type TrafficRequest_All struct {
	All bool `protobuf:"varint,2,opt,name=all,proto3,oneof"`
}

type TrafficRequest_WayId struct {
	WayId int64 `protobuf:"zigzag64,3,opt,name=wayId,proto3,oneof"`
}

type TrafficRequest_WayIds struct {
	WayIds *WayIdsStructure `protobuf:"bytes,4,opt,name=wayIds,proto3,oneof"`
}

func (*TrafficRequest_All) isTrafficRequest_WayIdFields() {}

func (*TrafficRequest_WayId) isTrafficRequest_WayIdFields() {}

func (*TrafficRequest_WayIds) isTrafficRequest_WayIdFields() {}

func (m *TrafficRequest) GetWayIdFields() isTrafficRequest_WayIdFields {
	if m != nil {
		return m.WayIdFields
	}
	return nil
}

func (m *TrafficRequest) GetAll() bool {
	if x, ok := m.GetWayIdFields().(*TrafficRequest_All); ok {
		return x.All
	}
	return false
}

func (m *TrafficRequest) GetWayId() int64 {
	if x, ok := m.GetWayIdFields().(*TrafficRequest_WayId); ok {
		return x.WayId
	}
	return 0
}

func (m *TrafficRequest) GetWayIds() *WayIdsStructure {
	if x, ok := m.GetWayIdFields().(*TrafficRequest_WayIds); ok {
		return x.WayIds
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TrafficRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TrafficRequest_All)(nil),
		(*TrafficRequest_WayId)(nil),
		(*TrafficRequest_WayIds)(nil),
	}
}

type TrafficResponse struct {
	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	// Types that are valid to be assigned to FlowFields:
	//	*TrafficResponse_Flow
	//	*TrafficResponse_Flows
	FlowFields           isTrafficResponse_FlowFields `protobuf_oneof:"FlowFields"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *TrafficResponse) Reset()         { *m = TrafficResponse{} }
func (m *TrafficResponse) String() string { return proto.CompactTextString(m) }
func (*TrafficResponse) ProtoMessage()    {}
func (*TrafficResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{5}
}

func (m *TrafficResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficResponse.Unmarshal(m, b)
}
func (m *TrafficResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficResponse.Marshal(b, m, deterministic)
}
func (m *TrafficResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficResponse.Merge(m, src)
}
func (m *TrafficResponse) XXX_Size() int {
	return xxx_messageInfo_TrafficResponse.Size(m)
}
func (m *TrafficResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficResponse proto.InternalMessageInfo

func (m *TrafficResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *TrafficResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type isTrafficResponse_FlowFields interface {
	isTrafficResponse_FlowFields()
}

type TrafficResponse_Flow struct {
	Flow *Flow `protobuf:"bytes,3,opt,name=flow,proto3,oneof"`
}

type TrafficResponse_Flows struct {
	Flows *FlowsStructure `protobuf:"bytes,4,opt,name=flows,proto3,oneof"`
}

func (*TrafficResponse_Flow) isTrafficResponse_FlowFields() {}

func (*TrafficResponse_Flows) isTrafficResponse_FlowFields() {}

func (m *TrafficResponse) GetFlowFields() isTrafficResponse_FlowFields {
	if m != nil {
		return m.FlowFields
	}
	return nil
}

func (m *TrafficResponse) GetFlow() *Flow {
	if x, ok := m.GetFlowFields().(*TrafficResponse_Flow); ok {
		return x.Flow
	}
	return nil
}

func (m *TrafficResponse) GetFlows() *FlowsStructure {
	if x, ok := m.GetFlowFields().(*TrafficResponse_Flows); ok {
		return x.Flows
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TrafficResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TrafficResponse_Flow)(nil),
		(*TrafficResponse_Flows)(nil),
	}
}

type TrafficStreamingRequest struct {
	TrafficSource        *TrafficSource                          `protobuf:"bytes,1,opt,name=trafficSource,proto3" json:"trafficSource,omitempty"`
	StreamingRules       *TrafficStreamingRequest_StreamingRules `protobuf:"bytes,2,opt,name=streamingRules,proto3" json:"streamingRules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *TrafficStreamingRequest) Reset()         { *m = TrafficStreamingRequest{} }
func (m *TrafficStreamingRequest) String() string { return proto.CompactTextString(m) }
func (*TrafficStreamingRequest) ProtoMessage()    {}
func (*TrafficStreamingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{6}
}

func (m *TrafficStreamingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficStreamingRequest.Unmarshal(m, b)
}
func (m *TrafficStreamingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficStreamingRequest.Marshal(b, m, deterministic)
}
func (m *TrafficStreamingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficStreamingRequest.Merge(m, src)
}
func (m *TrafficStreamingRequest) XXX_Size() int {
	return xxx_messageInfo_TrafficStreamingRequest.Size(m)
}
func (m *TrafficStreamingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficStreamingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficStreamingRequest proto.InternalMessageInfo

func (m *TrafficStreamingRequest) GetTrafficSource() *TrafficSource {
	if m != nil {
		return m.TrafficSource
	}
	return nil
}

func (m *TrafficStreamingRequest) GetStreamingRules() *TrafficStreamingRequest_StreamingRules {
	if m != nil {
		return m.StreamingRules
	}
	return nil
}

type TrafficStreamingRequest_StreamingRules struct {
	// send flows by streaming when flow_count >= maxSize or not_send_time_interval >= maxTime seconds
	MaxSize              int32    `protobuf:"varint,1,opt,name=maxSize,proto3" json:"maxSize,omitempty"`
	MaxTime              int32    `protobuf:"varint,2,opt,name=maxTime,proto3" json:"maxTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrafficStreamingRequest_StreamingRules) Reset() {
	*m = TrafficStreamingRequest_StreamingRules{}
}
func (m *TrafficStreamingRequest_StreamingRules) String() string { return proto.CompactTextString(m) }
func (*TrafficStreamingRequest_StreamingRules) ProtoMessage()    {}
func (*TrafficStreamingRequest_StreamingRules) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{6, 0}
}

func (m *TrafficStreamingRequest_StreamingRules) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficStreamingRequest_StreamingRules.Unmarshal(m, b)
}
func (m *TrafficStreamingRequest_StreamingRules) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficStreamingRequest_StreamingRules.Marshal(b, m, deterministic)
}
func (m *TrafficStreamingRequest_StreamingRules) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficStreamingRequest_StreamingRules.Merge(m, src)
}
func (m *TrafficStreamingRequest_StreamingRules) XXX_Size() int {
	return xxx_messageInfo_TrafficStreamingRequest_StreamingRules.Size(m)
}
func (m *TrafficStreamingRequest_StreamingRules) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficStreamingRequest_StreamingRules.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficStreamingRequest_StreamingRules proto.InternalMessageInfo

func (m *TrafficStreamingRequest_StreamingRules) GetMaxSize() int32 {
	if m != nil {
		return m.MaxSize
	}
	return 0
}

func (m *TrafficStreamingRequest_StreamingRules) GetMaxTime() int32 {
	if m != nil {
		return m.MaxTime
	}
	return 0
}

type TrafficStreamingResponse struct {
	// Types that are valid to be assigned to FlowFields:
	//	*TrafficStreamingResponse_Flow
	//	*TrafficStreamingResponse_Flows
	FlowFields           isTrafficStreamingResponse_FlowFields `protobuf_oneof:"FlowFields"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *TrafficStreamingResponse) Reset()         { *m = TrafficStreamingResponse{} }
func (m *TrafficStreamingResponse) String() string { return proto.CompactTextString(m) }
func (*TrafficStreamingResponse) ProtoMessage()    {}
func (*TrafficStreamingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{7}
}

func (m *TrafficStreamingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficStreamingResponse.Unmarshal(m, b)
}
func (m *TrafficStreamingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficStreamingResponse.Marshal(b, m, deterministic)
}
func (m *TrafficStreamingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficStreamingResponse.Merge(m, src)
}
func (m *TrafficStreamingResponse) XXX_Size() int {
	return xxx_messageInfo_TrafficStreamingResponse.Size(m)
}
func (m *TrafficStreamingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficStreamingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficStreamingResponse proto.InternalMessageInfo

type isTrafficStreamingResponse_FlowFields interface {
	isTrafficStreamingResponse_FlowFields()
}

type TrafficStreamingResponse_Flow struct {
	Flow *Flow `protobuf:"bytes,3,opt,name=flow,proto3,oneof"`
}

type TrafficStreamingResponse_Flows struct {
	Flows *FlowsStructure `protobuf:"bytes,4,opt,name=flows,proto3,oneof"`
}

func (*TrafficStreamingResponse_Flow) isTrafficStreamingResponse_FlowFields() {}

func (*TrafficStreamingResponse_Flows) isTrafficStreamingResponse_FlowFields() {}

func (m *TrafficStreamingResponse) GetFlowFields() isTrafficStreamingResponse_FlowFields {
	if m != nil {
		return m.FlowFields
	}
	return nil
}

func (m *TrafficStreamingResponse) GetFlow() *Flow {
	if x, ok := m.GetFlowFields().(*TrafficStreamingResponse_Flow); ok {
		return x.Flow
	}
	return nil
}

func (m *TrafficStreamingResponse) GetFlows() *FlowsStructure {
	if x, ok := m.GetFlowFields().(*TrafficStreamingResponse_Flows); ok {
		return x.Flows
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TrafficStreamingResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TrafficStreamingResponse_Flow)(nil),
		(*TrafficStreamingResponse_Flows)(nil),
	}
}

func init() {
	proto.RegisterType((*TrafficSource)(nil), "TrafficSource")
	proto.RegisterType((*WayIdsStructure)(nil), "WayIdsStructure")
	proto.RegisterType((*Flow)(nil), "Flow")
	proto.RegisterType((*FlowsStructure)(nil), "FlowsStructure")
	proto.RegisterType((*TrafficRequest)(nil), "TrafficRequest")
	proto.RegisterType((*TrafficResponse)(nil), "TrafficResponse")
	proto.RegisterType((*TrafficStreamingRequest)(nil), "TrafficStreamingRequest")
	proto.RegisterType((*TrafficStreamingRequest_StreamingRules)(nil), "TrafficStreamingRequest.StreamingRules")
	proto.RegisterType((*TrafficStreamingResponse)(nil), "TrafficStreamingResponse")
}

func init() { proto.RegisterFile("proxy.proto", fileDescriptor_700b50b08ed8dbaf) }

var fileDescriptor_700b50b08ed8dbaf = []byte{
	// 512 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x5d, 0x8e, 0xd3, 0x3c,
	0x14, 0x8d, 0xa7, 0x3f, 0xdf, 0x7c, 0x37, 0xfd, 0xc3, 0x42, 0x43, 0xa6, 0x48, 0xa8, 0xf2, 0x4b,
	0x2b, 0x90, 0xcc, 0xa8, 0xb0, 0x82, 0x0a, 0x0d, 0x45, 0x1a, 0x89, 0x91, 0x5b, 0xc1, 0x73, 0x48,
	0xdc, 0x2a, 0x52, 0x12, 0x07, 0x3b, 0xe9, 0x0f, 0x5b, 0x40, 0x2c, 0x85, 0x6d, 0xb1, 0x0e, 0x64,
	0xc7, 0x89, 0x9a, 0xa2, 0x3e, 0x21, 0x9e, 0xea, 0x7b, 0xcf, 0xb1, 0xcf, 0xb9, 0xc7, 0x6e, 0xc0,
	0xcd, 0xa4, 0x38, 0x1c, 0x69, 0x26, 0x45, 0x2e, 0x88, 0x82, 0xfe, 0x5a, 0xfa, 0x9b, 0x4d, 0x14,
	0xac, 0x44, 0x21, 0x03, 0x8e, 0x6f, 0xa0, 0x2b, 0xf9, 0x36, 0x12, 0xa9, 0x87, 0x26, 0x68, 0xf6,
	0x3f, 0xb3, 0x15, 0x9e, 0xc1, 0x30, 0x2f, 0x89, 0x8f, 0x52, 0xec, 0xa2, 0x90, 0x4b, 0xef, 0xca,
	0x10, 0xce, 0xdb, 0x78, 0x02, 0x6e, 0xe2, 0x67, 0x35, 0xab, 0x65, 0x58, 0xa7, 0x2d, 0x32, 0x85,
	0xe1, 0x67, 0xff, 0xf8, 0x21, 0x54, 0xab, 0x5c, 0x16, 0x41, 0x5e, 0x48, 0x8e, 0x9f, 0x42, 0x67,
	0xaf, 0x5b, 0x1e, 0x9a, 0xb4, 0x66, 0x98, 0x95, 0x05, 0xf9, 0x04, 0xed, 0xfb, 0x58, 0xec, 0x4f,
	0x51, 0x54, 0xa3, 0xba, 0xab, 0x32, 0xce, 0x43, 0x63, 0xe4, 0x8a, 0x95, 0x05, 0x26, 0xd0, 0xb3,
	0x8e, 0x1e, 0xf8, 0x8e, 0xc7, 0x46, 0xbf, 0xc3, 0x1a, 0x3d, 0xf2, 0x0a, 0x06, 0xfa, 0xdc, 0x13,
	0xfd, 0x5b, 0x68, 0x6f, 0x62, 0xb1, 0x37, 0xf2, 0xee, 0xbc, 0x43, 0x35, 0xcc, 0x4c, 0x8b, 0xfc,
	0x44, 0x30, 0xb0, 0x19, 0x31, 0xfe, 0xb5, 0xe0, 0x2a, 0xc7, 0x6f, 0xa1, 0x9f, 0x9f, 0xa6, 0x66,
	0x7c, 0xb9, 0xf3, 0x01, 0x6d, 0x64, 0xc9, 0x9a, 0x24, 0x8c, 0xa1, 0xe5, 0xc7, 0xb1, 0x71, 0x7b,
	0xbd, 0x74, 0x98, 0x2e, 0xf0, 0x4d, 0x35, 0x99, 0xb6, 0x89, 0x97, 0x4e, 0x35, 0xdb, 0x4b, 0xe8,
	0x9a, 0x85, 0xf2, 0xda, 0xe6, 0xe8, 0x11, 0x3d, 0x4b, 0x6c, 0xe9, 0x30, 0xcb, 0x58, 0xf4, 0xc1,
	0x35, 0xe0, 0x7d, 0xc4, 0xe3, 0x50, 0x91, 0xef, 0x08, 0x86, 0xb5, 0x5f, 0x95, 0x89, 0x54, 0x69,
	0xe9, 0x76, 0x20, 0xc2, 0xd2, 0x67, 0x87, 0x99, 0x35, 0x1e, 0x41, 0x2b, 0x51, 0x5b, 0x7b, 0x8b,
	0x7a, 0x89, 0x9f, 0xdb, 0x10, 0x5a, 0x46, 0xb2, 0x0c, 0x61, 0xe9, 0x94, 0x31, 0xe0, 0x29, 0x74,
	0xf4, 0x6f, 0x65, 0x68, 0x48, 0x9b, 0x09, 0x6a, 0xeb, 0x06, 0x5f, 0xf4, 0x00, 0x34, 0x64, 0xdd,
	0xfc, 0x42, 0xf0, 0xac, 0x4a, 0x25, 0x97, 0xdc, 0x4f, 0xa2, 0x74, 0xfb, 0x77, 0x31, 0x7e, 0x84,
	0x81, 0xaa, 0x4f, 0x2a, 0x62, 0xae, 0xcc, 0x08, 0xee, 0x7c, 0x4a, 0x2f, 0xe8, 0xd0, 0x55, 0x83,
	0xce, 0xce, 0xb6, 0x8f, 0xdf, 0xc1, 0xa0, 0xc9, 0xc0, 0x1e, 0xfc, 0x97, 0xf8, 0x87, 0x55, 0xf4,
	0xad, 0x4a, 0xac, 0x2a, 0x2d, 0xb2, 0x8e, 0x12, 0x6e, 0x54, 0x4b, 0x44, 0x97, 0x24, 0x05, 0xef,
	0x4f, 0x7d, 0x1b, 0xff, 0x3f, 0x08, 0x76, 0xfe, 0x03, 0x41, 0x6f, 0x5d, 0xff, 0xf5, 0x0e, 0x47,
	0xfc, 0x1a, 0xae, 0xdf, 0xf3, 0xdc, 0x6c, 0xc6, 0x43, 0xda, 0x7c, 0xb1, 0xe3, 0x11, 0x3d, 0x7b,
	0x12, 0xc4, 0xc1, 0x0f, 0xf0, 0xa4, 0xda, 0x50, 0x5b, 0xc6, 0xde, 0xa5, 0x14, 0xc7, 0xb7, 0xf4,
	0xd2, 0x7c, 0xc4, 0xb9, 0x43, 0x8b, 0x3b, 0x78, 0x11, 0x88, 0x84, 0xe6, 0x3c, 0xe6, 0xa9, 0xbf,
	0xa3, 0xf6, 0xce, 0xe8, 0x56, 0x66, 0x41, 0xf9, 0xad, 0x59, 0x34, 0xec, 0x3e, 0xa2, 0x2f, 0x5d,
	0xd3, 0x7e, 0xf3, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x12, 0xf2, 0x31, 0xc4, 0x91, 0x04, 0x00, 0x00,
}
