// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proxy.proto

package proxy

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TrafficSource struct {
	Region               string   `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	TrafficProvider      string   `protobuf:"bytes,2,opt,name=trafficProvider,proto3" json:"trafficProvider,omitempty"`
	MapProvider          string   `protobuf:"bytes,3,opt,name=mapProvider,proto3" json:"mapProvider,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrafficSource) Reset()         { *m = TrafficSource{} }
func (m *TrafficSource) String() string { return proto.CompactTextString(m) }
func (*TrafficSource) ProtoMessage()    {}
func (*TrafficSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{0}
}

func (m *TrafficSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficSource.Unmarshal(m, b)
}
func (m *TrafficSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficSource.Marshal(b, m, deterministic)
}
func (m *TrafficSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficSource.Merge(m, src)
}
func (m *TrafficSource) XXX_Size() int {
	return xxx_messageInfo_TrafficSource.Size(m)
}
func (m *TrafficSource) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficSource.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficSource proto.InternalMessageInfo

func (m *TrafficSource) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *TrafficSource) GetTrafficProvider() string {
	if m != nil {
		return m.TrafficProvider
	}
	return ""
}

func (m *TrafficSource) GetMapProvider() string {
	if m != nil {
		return m.MapProvider
	}
	return ""
}

type WayIdsStructure struct {
	WayIds               []int64  `protobuf:"zigzag64,1,rep,packed,name=wayIds,proto3" json:"wayIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WayIdsStructure) Reset()         { *m = WayIdsStructure{} }
func (m *WayIdsStructure) String() string { return proto.CompactTextString(m) }
func (*WayIdsStructure) ProtoMessage()    {}
func (*WayIdsStructure) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{1}
}

func (m *WayIdsStructure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WayIdsStructure.Unmarshal(m, b)
}
func (m *WayIdsStructure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WayIdsStructure.Marshal(b, m, deterministic)
}
func (m *WayIdsStructure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WayIdsStructure.Merge(m, src)
}
func (m *WayIdsStructure) XXX_Size() int {
	return xxx_messageInfo_WayIdsStructure.Size(m)
}
func (m *WayIdsStructure) XXX_DiscardUnknown() {
	xxx_messageInfo_WayIdsStructure.DiscardUnknown(m)
}

var xxx_messageInfo_WayIdsStructure proto.InternalMessageInfo

func (m *WayIdsStructure) GetWayIds() []int64 {
	if m != nil {
		return m.WayIds
	}
	return nil
}

type Flow struct {
	WayId                int64    `protobuf:"zigzag64,1,opt,name=wayId,proto3" json:"wayId,omitempty"`
	Speed                float32  `protobuf:"fixed32,2,opt,name=speed,proto3" json:"speed,omitempty"`
	TrafficLevel         int32    `protobuf:"varint,3,opt,name=trafficLevel,proto3" json:"trafficLevel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Flow) Reset()         { *m = Flow{} }
func (m *Flow) String() string { return proto.CompactTextString(m) }
func (*Flow) ProtoMessage()    {}
func (*Flow) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{2}
}

func (m *Flow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Flow.Unmarshal(m, b)
}
func (m *Flow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Flow.Marshal(b, m, deterministic)
}
func (m *Flow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Flow.Merge(m, src)
}
func (m *Flow) XXX_Size() int {
	return xxx_messageInfo_Flow.Size(m)
}
func (m *Flow) XXX_DiscardUnknown() {
	xxx_messageInfo_Flow.DiscardUnknown(m)
}

var xxx_messageInfo_Flow proto.InternalMessageInfo

func (m *Flow) GetWayId() int64 {
	if m != nil {
		return m.WayId
	}
	return 0
}

func (m *Flow) GetSpeed() float32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *Flow) GetTrafficLevel() int32 {
	if m != nil {
		return m.TrafficLevel
	}
	return 0
}

type FlowsStructure struct {
	Flows                []*Flow  `protobuf:"bytes,1,rep,name=flows,proto3" json:"flows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlowsStructure) Reset()         { *m = FlowsStructure{} }
func (m *FlowsStructure) String() string { return proto.CompactTextString(m) }
func (*FlowsStructure) ProtoMessage()    {}
func (*FlowsStructure) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{3}
}

func (m *FlowsStructure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlowsStructure.Unmarshal(m, b)
}
func (m *FlowsStructure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlowsStructure.Marshal(b, m, deterministic)
}
func (m *FlowsStructure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlowsStructure.Merge(m, src)
}
func (m *FlowsStructure) XXX_Size() int {
	return xxx_messageInfo_FlowsStructure.Size(m)
}
func (m *FlowsStructure) XXX_DiscardUnknown() {
	xxx_messageInfo_FlowsStructure.DiscardUnknown(m)
}

var xxx_messageInfo_FlowsStructure proto.InternalMessageInfo

func (m *FlowsStructure) GetFlows() []*Flow {
	if m != nil {
		return m.Flows
	}
	return nil
}

type TrafficRequest struct {
	TrafficSource *TrafficSource `protobuf:"bytes,1,opt,name=trafficSource,proto3" json:"trafficSource,omitempty"`
	// Types that are valid to be assigned to WayIdFields:
	//	*TrafficRequest_All
	//	*TrafficRequest_WayId
	//	*TrafficRequest_WayIds
	WayIdFields          isTrafficRequest_WayIdFields `protobuf_oneof:"WayIdFields"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *TrafficRequest) Reset()         { *m = TrafficRequest{} }
func (m *TrafficRequest) String() string { return proto.CompactTextString(m) }
func (*TrafficRequest) ProtoMessage()    {}
func (*TrafficRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{4}
}

func (m *TrafficRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficRequest.Unmarshal(m, b)
}
func (m *TrafficRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficRequest.Marshal(b, m, deterministic)
}
func (m *TrafficRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficRequest.Merge(m, src)
}
func (m *TrafficRequest) XXX_Size() int {
	return xxx_messageInfo_TrafficRequest.Size(m)
}
func (m *TrafficRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficRequest proto.InternalMessageInfo

func (m *TrafficRequest) GetTrafficSource() *TrafficSource {
	if m != nil {
		return m.TrafficSource
	}
	return nil
}

type isTrafficRequest_WayIdFields interface {
	isTrafficRequest_WayIdFields()
}

type TrafficRequest_All struct {
	All bool `protobuf:"varint,2,opt,name=all,proto3,oneof"`
}

type TrafficRequest_WayId struct {
	WayId int64 `protobuf:"zigzag64,3,opt,name=wayId,proto3,oneof"`
}

type TrafficRequest_WayIds struct {
	WayIds *WayIdsStructure `protobuf:"bytes,4,opt,name=wayIds,proto3,oneof"`
}

func (*TrafficRequest_All) isTrafficRequest_WayIdFields() {}

func (*TrafficRequest_WayId) isTrafficRequest_WayIdFields() {}

func (*TrafficRequest_WayIds) isTrafficRequest_WayIdFields() {}

func (m *TrafficRequest) GetWayIdFields() isTrafficRequest_WayIdFields {
	if m != nil {
		return m.WayIdFields
	}
	return nil
}

func (m *TrafficRequest) GetAll() bool {
	if x, ok := m.GetWayIdFields().(*TrafficRequest_All); ok {
		return x.All
	}
	return false
}

func (m *TrafficRequest) GetWayId() int64 {
	if x, ok := m.GetWayIdFields().(*TrafficRequest_WayId); ok {
		return x.WayId
	}
	return 0
}

func (m *TrafficRequest) GetWayIds() *WayIdsStructure {
	if x, ok := m.GetWayIdFields().(*TrafficRequest_WayIds); ok {
		return x.WayIds
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TrafficRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TrafficRequest_All)(nil),
		(*TrafficRequest_WayId)(nil),
		(*TrafficRequest_WayIds)(nil),
	}
}

type TrafficResponse struct {
	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	// Types that are valid to be assigned to FlowFields:
	//	*TrafficResponse_Flow
	//	*TrafficResponse_Flows
	FlowFields           isTrafficResponse_FlowFields `protobuf_oneof:"FlowFields"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *TrafficResponse) Reset()         { *m = TrafficResponse{} }
func (m *TrafficResponse) String() string { return proto.CompactTextString(m) }
func (*TrafficResponse) ProtoMessage()    {}
func (*TrafficResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{5}
}

func (m *TrafficResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficResponse.Unmarshal(m, b)
}
func (m *TrafficResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficResponse.Marshal(b, m, deterministic)
}
func (m *TrafficResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficResponse.Merge(m, src)
}
func (m *TrafficResponse) XXX_Size() int {
	return xxx_messageInfo_TrafficResponse.Size(m)
}
func (m *TrafficResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficResponse proto.InternalMessageInfo

func (m *TrafficResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *TrafficResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type isTrafficResponse_FlowFields interface {
	isTrafficResponse_FlowFields()
}

type TrafficResponse_Flow struct {
	Flow *Flow `protobuf:"bytes,3,opt,name=flow,proto3,oneof"`
}

type TrafficResponse_Flows struct {
	Flows *FlowsStructure `protobuf:"bytes,4,opt,name=flows,proto3,oneof"`
}

func (*TrafficResponse_Flow) isTrafficResponse_FlowFields() {}

func (*TrafficResponse_Flows) isTrafficResponse_FlowFields() {}

func (m *TrafficResponse) GetFlowFields() isTrafficResponse_FlowFields {
	if m != nil {
		return m.FlowFields
	}
	return nil
}

func (m *TrafficResponse) GetFlow() *Flow {
	if x, ok := m.GetFlowFields().(*TrafficResponse_Flow); ok {
		return x.Flow
	}
	return nil
}

func (m *TrafficResponse) GetFlows() *FlowsStructure {
	if x, ok := m.GetFlowFields().(*TrafficResponse_Flows); ok {
		return x.Flows
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TrafficResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TrafficResponse_Flow)(nil),
		(*TrafficResponse_Flows)(nil),
	}
}

type TrafficStreamingRequest struct {
	TrafficSource        *TrafficSource                          `protobuf:"bytes,1,opt,name=trafficSource,proto3" json:"trafficSource,omitempty"`
	StreamingRules       *TrafficStreamingRequest_StreamingRules `protobuf:"bytes,2,opt,name=streamingRules,proto3" json:"streamingRules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *TrafficStreamingRequest) Reset()         { *m = TrafficStreamingRequest{} }
func (m *TrafficStreamingRequest) String() string { return proto.CompactTextString(m) }
func (*TrafficStreamingRequest) ProtoMessage()    {}
func (*TrafficStreamingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{6}
}

func (m *TrafficStreamingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficStreamingRequest.Unmarshal(m, b)
}
func (m *TrafficStreamingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficStreamingRequest.Marshal(b, m, deterministic)
}
func (m *TrafficStreamingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficStreamingRequest.Merge(m, src)
}
func (m *TrafficStreamingRequest) XXX_Size() int {
	return xxx_messageInfo_TrafficStreamingRequest.Size(m)
}
func (m *TrafficStreamingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficStreamingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficStreamingRequest proto.InternalMessageInfo

func (m *TrafficStreamingRequest) GetTrafficSource() *TrafficSource {
	if m != nil {
		return m.TrafficSource
	}
	return nil
}

func (m *TrafficStreamingRequest) GetStreamingRules() *TrafficStreamingRequest_StreamingRules {
	if m != nil {
		return m.StreamingRules
	}
	return nil
}

type TrafficStreamingRequest_StreamingRules struct {
	// send flows by streaming when flow_count >= maxSize or not_send_time_interval >= maxTime seconds
	MaxSize              int32    `protobuf:"varint,1,opt,name=maxSize,proto3" json:"maxSize,omitempty"`
	MaxTime              int32    `protobuf:"varint,2,opt,name=maxTime,proto3" json:"maxTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrafficStreamingRequest_StreamingRules) Reset() {
	*m = TrafficStreamingRequest_StreamingRules{}
}
func (m *TrafficStreamingRequest_StreamingRules) String() string { return proto.CompactTextString(m) }
func (*TrafficStreamingRequest_StreamingRules) ProtoMessage()    {}
func (*TrafficStreamingRequest_StreamingRules) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{6, 0}
}

func (m *TrafficStreamingRequest_StreamingRules) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficStreamingRequest_StreamingRules.Unmarshal(m, b)
}
func (m *TrafficStreamingRequest_StreamingRules) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficStreamingRequest_StreamingRules.Marshal(b, m, deterministic)
}
func (m *TrafficStreamingRequest_StreamingRules) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficStreamingRequest_StreamingRules.Merge(m, src)
}
func (m *TrafficStreamingRequest_StreamingRules) XXX_Size() int {
	return xxx_messageInfo_TrafficStreamingRequest_StreamingRules.Size(m)
}
func (m *TrafficStreamingRequest_StreamingRules) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficStreamingRequest_StreamingRules.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficStreamingRequest_StreamingRules proto.InternalMessageInfo

func (m *TrafficStreamingRequest_StreamingRules) GetMaxSize() int32 {
	if m != nil {
		return m.MaxSize
	}
	return 0
}

func (m *TrafficStreamingRequest_StreamingRules) GetMaxTime() int32 {
	if m != nil {
		return m.MaxTime
	}
	return 0
}

type TrafficStreamingResponse struct {
	Flows                *FlowsStructure `protobuf:"bytes,1,opt,name=flows,proto3" json:"flows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TrafficStreamingResponse) Reset()         { *m = TrafficStreamingResponse{} }
func (m *TrafficStreamingResponse) String() string { return proto.CompactTextString(m) }
func (*TrafficStreamingResponse) ProtoMessage()    {}
func (*TrafficStreamingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{7}
}

func (m *TrafficStreamingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficStreamingResponse.Unmarshal(m, b)
}
func (m *TrafficStreamingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficStreamingResponse.Marshal(b, m, deterministic)
}
func (m *TrafficStreamingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficStreamingResponse.Merge(m, src)
}
func (m *TrafficStreamingResponse) XXX_Size() int {
	return xxx_messageInfo_TrafficStreamingResponse.Size(m)
}
func (m *TrafficStreamingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficStreamingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficStreamingResponse proto.InternalMessageInfo

func (m *TrafficStreamingResponse) GetFlows() *FlowsStructure {
	if m != nil {
		return m.Flows
	}
	return nil
}

func init() {
	proto.RegisterType((*TrafficSource)(nil), "proxy.TrafficSource")
	proto.RegisterType((*WayIdsStructure)(nil), "proxy.WayIdsStructure")
	proto.RegisterType((*Flow)(nil), "proxy.Flow")
	proto.RegisterType((*FlowsStructure)(nil), "proxy.FlowsStructure")
	proto.RegisterType((*TrafficRequest)(nil), "proxy.TrafficRequest")
	proto.RegisterType((*TrafficResponse)(nil), "proxy.TrafficResponse")
	proto.RegisterType((*TrafficStreamingRequest)(nil), "proxy.TrafficStreamingRequest")
	proto.RegisterType((*TrafficStreamingRequest_StreamingRules)(nil), "proxy.TrafficStreamingRequest.StreamingRules")
	proto.RegisterType((*TrafficStreamingResponse)(nil), "proxy.TrafficStreamingResponse")
}

func init() { proto.RegisterFile("proxy.proto", fileDescriptor_700b50b08ed8dbaf) }

var fileDescriptor_700b50b08ed8dbaf = []byte{
	// 530 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xcd, 0x6e, 0xda, 0x4e,
	0x14, 0xc5, 0x71, 0x80, 0xfc, 0xf3, 0xbf, 0xe6, 0xa3, 0xbd, 0x4a, 0x28, 0x62, 0x91, 0x12, 0xaf,
	0xa8, 0xaa, 0x58, 0x88, 0xec, 0xda, 0x1d, 0xaa, 0x12, 0x2a, 0x75, 0x11, 0x0d, 0xf4, 0x63, 0xeb,
	0x9a, 0x01, 0x59, 0xb2, 0x19, 0x77, 0xc6, 0x10, 0xe8, 0x8b, 0xf4, 0x09, 0xfa, 0x10, 0x7d, 0xad,
	0x3e, 0x41, 0x35, 0x77, 0xc6, 0x2e, 0x76, 0x95, 0xae, 0xba, 0xf3, 0x3d, 0xf7, 0xcc, 0xdc, 0xdf,
	0x3d, 0x93, 0x00, 0x6e, 0x2a, 0xc5, 0xfe, 0xe0, 0xa7, 0x52, 0x64, 0x02, 0x9b, 0x54, 0x78, 0x0a,
	0xda, 0x0b, 0x19, 0xac, 0x56, 0x51, 0x38, 0x17, 0x5b, 0x19, 0x72, 0xec, 0xc1, 0xa9, 0xe4, 0xeb,
	0x48, 0x6c, 0xfa, 0xce, 0xd0, 0x19, 0xfd, 0xcf, 0x6c, 0x85, 0x23, 0xe8, 0x66, 0xc6, 0x78, 0x2f,
	0xc5, 0x2e, 0x5a, 0x72, 0xd9, 0x3f, 0x21, 0x43, 0x55, 0xc6, 0x21, 0xb8, 0x49, 0x90, 0x16, 0xae,
	0x3a, 0xb9, 0x8e, 0x25, 0xef, 0x05, 0x74, 0x3f, 0x06, 0x87, 0xb7, 0x4b, 0x35, 0xcf, 0xe4, 0x36,
	0xcc, 0xb6, 0x92, 0xc6, 0x3e, 0x90, 0xd4, 0x77, 0x86, 0xf5, 0x11, 0x32, 0x5b, 0x79, 0x1f, 0xa0,
	0x71, 0x1b, 0x8b, 0x07, 0x3c, 0x87, 0x26, 0x29, 0x44, 0x85, 0xcc, 0x14, 0x5a, 0x55, 0x29, 0xe7,
	0x4b, 0x42, 0x39, 0x61, 0xa6, 0x40, 0x0f, 0x5a, 0x96, 0xe9, 0x1d, 0xdf, 0xf1, 0x98, 0x08, 0x9a,
	0xac, 0xa4, 0x79, 0x37, 0xd0, 0xd1, 0xf7, 0x1e, 0x11, 0x5c, 0x41, 0x73, 0xa5, 0x15, 0x02, 0x70,
	0x27, 0xae, 0x6f, 0xd2, 0xd2, 0x2e, 0x66, 0x3a, 0xde, 0x0f, 0x07, 0x3a, 0x36, 0x2d, 0xc6, 0xbf,
	0x6c, 0xb9, 0xca, 0xf0, 0x15, 0xb4, 0xb3, 0xe3, 0xfc, 0x88, 0xcf, 0x9d, 0x9c, 0xdb, 0xd3, 0xa5,
	0x6c, 0x59, 0xd9, 0x8a, 0x08, 0xf5, 0x20, 0x8e, 0x89, 0xfd, 0x6c, 0x56, 0x63, 0xba, 0xc0, 0x5e,
	0xbe, 0xa7, 0x86, 0xc6, 0x59, 0x2d, 0xdf, 0x74, 0x5c, 0xe4, 0xd3, 0xa0, 0x01, 0x3d, 0x3b, 0xa0,
	0x92, 0xe3, 0xac, 0x96, 0x27, 0x37, 0x6d, 0x83, 0x4b, 0xcd, 0xdb, 0x88, 0xc7, 0x4b, 0xe5, 0x7d,
	0x73, 0xa0, 0x5b, 0xb0, 0xab, 0x54, 0x6c, 0x94, 0x06, 0x68, 0x84, 0x62, 0x69, 0x98, 0x9b, 0x8c,
	0xbe, 0xf1, 0x09, 0xd4, 0x13, 0xb5, 0xb6, 0x6f, 0xab, 0x3f, 0xf1, 0x0a, 0x1a, 0x7a, 0x7d, 0x22,
	0x2a, 0xe7, 0x32, 0xab, 0x31, 0x6a, 0xe1, 0x75, 0x9e, 0x9d, 0x81, 0xbb, 0x38, 0xf2, 0x94, 0xd8,
	0x8c, 0x6b, 0xda, 0x02, 0xd0, 0x2d, 0x4b, 0xf6, 0xd3, 0x81, 0x67, 0x79, 0x4e, 0x99, 0xe4, 0x41,
	0x12, 0x6d, 0xd6, 0xff, 0x22, 0xde, 0xf7, 0xd0, 0x51, 0xc5, 0x7d, 0xdb, 0x98, 0x2b, 0x5a, 0xca,
	0x9d, 0x5c, 0x57, 0x0e, 0x57, 0x66, 0xfa, 0xf3, 0xd2, 0x21, 0x56, 0xb9, 0x64, 0xf0, 0x06, 0x3a,
	0x65, 0x07, 0xf6, 0xe1, 0xbf, 0x24, 0xd8, 0xcf, 0xa3, 0xaf, 0x79, 0x92, 0x79, 0x69, 0x3b, 0x8b,
	0x28, 0xe1, 0x34, 0xdb, 0x74, 0x74, 0xe9, 0xdd, 0x41, 0xff, 0xcf, 0xf9, 0xf6, 0x59, 0x5e, 0xfe,
	0xfe, 0x4b, 0x7c, 0x3c, 0x4d, 0x9b, 0xe5, 0xe4, 0xbb, 0x03, 0xad, 0x45, 0xf1, 0x1f, 0xb8, 0x3f,
	0xe0, 0x6b, 0x38, 0xbb, 0xe3, 0x19, 0x99, 0xf1, 0xa2, 0xbc, 0xaa, 0xdd, 0x70, 0xd0, 0xab, 0xca,
	0x66, 0xb0, 0x57, 0xc3, 0x4f, 0xf0, 0x34, 0x3f, 0x5c, 0x70, 0xe1, 0xe5, 0xdf, 0x03, 0x1b, 0x3c,
	0x7f, 0xb4, 0x9f, 0xdf, 0x3b, 0x76, 0xa6, 0x63, 0xb8, 0x0c, 0x45, 0xe2, 0x67, 0x3c, 0xe6, 0x9b,
	0x60, 0xe7, 0xdb, 0xa7, 0xf2, 0xd7, 0x32, 0x0d, 0xcd, 0x2f, 0xd2, 0xb4, 0xb4, 0xc6, 0xbd, 0xf3,
	0xf9, 0x94, 0xe4, 0x9b, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x09, 0x97, 0x6b, 0xb7, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TrafficProxyClient is the client API for TrafficProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TrafficProxyClient interface {
	GetFlows(ctx context.Context, in *TrafficRequest, opts ...grpc.CallOption) (*TrafficResponse, error)
	GetFlowsStreaming(ctx context.Context, in *TrafficStreamingRequest, opts ...grpc.CallOption) (TrafficProxy_GetFlowsStreamingClient, error)
}

type trafficProxyClient struct {
	cc *grpc.ClientConn
}

func NewTrafficProxyClient(cc *grpc.ClientConn) TrafficProxyClient {
	return &trafficProxyClient{cc}
}

func (c *trafficProxyClient) GetFlows(ctx context.Context, in *TrafficRequest, opts ...grpc.CallOption) (*TrafficResponse, error) {
	out := new(TrafficResponse)
	err := c.cc.Invoke(ctx, "/proxy.TrafficProxy/GetFlows", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trafficProxyClient) GetFlowsStreaming(ctx context.Context, in *TrafficStreamingRequest, opts ...grpc.CallOption) (TrafficProxy_GetFlowsStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TrafficProxy_serviceDesc.Streams[0], "/proxy.TrafficProxy/GetFlowsStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &trafficProxyGetFlowsStreamingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TrafficProxy_GetFlowsStreamingClient interface {
	Recv() (*TrafficStreamingResponse, error)
	grpc.ClientStream
}

type trafficProxyGetFlowsStreamingClient struct {
	grpc.ClientStream
}

func (x *trafficProxyGetFlowsStreamingClient) Recv() (*TrafficStreamingResponse, error) {
	m := new(TrafficStreamingResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TrafficProxyServer is the server API for TrafficProxy service.
type TrafficProxyServer interface {
	GetFlows(context.Context, *TrafficRequest) (*TrafficResponse, error)
	GetFlowsStreaming(*TrafficStreamingRequest, TrafficProxy_GetFlowsStreamingServer) error
}

// UnimplementedTrafficProxyServer can be embedded to have forward compatible implementations.
type UnimplementedTrafficProxyServer struct {
}

func (*UnimplementedTrafficProxyServer) GetFlows(ctx context.Context, req *TrafficRequest) (*TrafficResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlows not implemented")
}
func (*UnimplementedTrafficProxyServer) GetFlowsStreaming(req *TrafficStreamingRequest, srv TrafficProxy_GetFlowsStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method GetFlowsStreaming not implemented")
}

func RegisterTrafficProxyServer(s *grpc.Server, srv TrafficProxyServer) {
	s.RegisterService(&_TrafficProxy_serviceDesc, srv)
}

func _TrafficProxy_GetFlows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrafficRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrafficProxyServer).GetFlows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proxy.TrafficProxy/GetFlows",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrafficProxyServer).GetFlows(ctx, req.(*TrafficRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrafficProxy_GetFlowsStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TrafficStreamingRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TrafficProxyServer).GetFlowsStreaming(m, &trafficProxyGetFlowsStreamingServer{stream})
}

type TrafficProxy_GetFlowsStreamingServer interface {
	Send(*TrafficStreamingResponse) error
	grpc.ServerStream
}

type trafficProxyGetFlowsStreamingServer struct {
	grpc.ServerStream
}

func (x *trafficProxyGetFlowsStreamingServer) Send(m *TrafficStreamingResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _TrafficProxy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proxy.TrafficProxy",
	HandlerType: (*TrafficProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFlows",
			Handler:    _TrafficProxy_GetFlows_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetFlowsStreaming",
			Handler:       _TrafficProxy_GetFlowsStreaming_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proxy.proto",
}
